controller_list:
  - name: fake_right_arm_controller
    joints:
      - arm_joint1
      - arm_joint2.0
      - arm_joint3.0
      - arm_joint4.0
      - arm_joint5.0
  - name: fake_right_hand_controller
    joints:
      - arm_joint5.0