 controller_list:
   - name: r_arm_controller
     action_ns: follow_joint_trajectory
     type: FollowJointTrajectory
     default: true
     joints:
       - arm_joint1
       - arm_joint2
       - arm_joint3
       - arm_joint4
       - arm_joint5
